@startuml
class Persona {
	edad
	
	inteligencia()
	potencia()
	esDestacado()
	darTributo(unPlaneta)
    valor()
}

Persona .up.> Planeta

class Atleta extends Persona {
	masaMuscular
	cantidadDeTecnicas
	
	potencia()
	esDestacado()
	entrenar(unosDias)
	aprenderUnaTecnica()
	darTributo(unPlaneta)
}
	
class Docente extends Persona {
	cantidadDeCursos
	 
	inteligencia()
	esDestacado()
	darTributo(unPlaneta)
    valor()
}

class Soldado extends Persona {
	arsenal
	potencia()
	darTributo(unPlaneta)
	potenciaDelArsenal()
}

abstract class Arma {
	{abstract}potencia(unSoldado)
}

class Pistolete extends Arma {
	largoEnCm
	potencia(unSoldado)
}

class Espadon extends Arma {
	pesoEnKg
	potencia(unSoldado)
}

Soldado -->"*" Arma : arsenal
Arma ..> Soldado


class Planeta {
	habitantes
	cantidadDeMuseos
	longitudDeMurallas
	
	delegacionDiplomatica()
	esCulto()
	potenciaReal()
	construirMurallas(unaCantidad)
	fundarMuseo()
	potenciaAparente()
	necesitaReforzarse()
	recibirTributo()
}

Planeta -->"*"Persona : habitantes

@enduml